# Generated by Django 2.2.7 on 2019-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttedanceManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2019-11-23'),
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
